stages:
  - build

build_release:
  only:
    - tags
  tags:
    - docker
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --build-arg BUILD_DATE=$(now) --build-arg VCS_REF=$CI_COMMIT_TAG --build-arg VCS_URL=$CI_REPOSITORY_URL .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

build_head:
  only:
    - master
  tags:
    - docker
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --build-arg BUILD_DATE=$(now) --build-arg VCS_REF=$CI_COMMIT_SHA --build-arg VCS_URL=$CI_REPOSITORY_URL .
    - docker push $CI_REGISTRY_IMAGE:latest
